//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWatchers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdonhang
    {
        public int id_donhang { get; set; }
        public string masp { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual dongho dongho { get; set; }
    }
}
