//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWatchers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dongho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dongho()
        {
            this.chitietbanhangs = new HashSet<chitietbanhang>();
            this.chitietdonhangs = new HashSet<chitietdonhang>();
            this.chitietnhaphangs = new HashSet<chitietnhaphang>();
            this.dongho_seri = new HashSet<dongho_seri>();
            this.hinhanhs = new HashSet<hinhanh>();
        }
    
        public string masp { get; set; }
        public string loai { get; set; }
        public string thuonghieu { get; set; }
        public string tensp { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<int> baohanh { get; set; }
        public Nullable<int> id_loai { get; set; }
        public Nullable<bool> act { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietbanhang> chitietbanhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdonhang> chitietdonhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietnhaphang> chitietnhaphangs { get; set; }
        public virtual loai loai1 { get; set; }
        public virtual thuonghieu thuonghieu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dongho_seri> dongho_seri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hinhanh> hinhanhs { get; set; }
        public virtual motachitiet motachitiet { get; set; }
    }
}
