//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWatchers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hinhanh
    {
        public int id_hinhanh { get; set; }
        public string masp { get; set; }
        public string duongdan { get; set; }
    
        public virtual dongho dongho { get; set; }
    }
}
