//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWatchers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon_nh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoadon_nh()
        {
            this.chitietnhaphangs = new HashSet<chitietnhaphang>();
        }
    
        public System.DateTime ngaylap { get; set; }
        public string manv { get; set; }
        public int stt_hd { get; set; }
        public Nullable<int> mancc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietnhaphang> chitietnhaphangs { get; set; }
        public virtual nhanvien nhanvien { get; set; }
        public virtual nhacungcap nhacungcap { get; set; }
    }
}
