//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWatchers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachhang()
        {
            this.donhangs = new HashSet<donhang>();
            this.hoadon_bh = new HashSet<hoadon_bh>();
        }
        [DisplayName("Tên KH")]
        public string tenkh { get; set; }
        [DisplayName("Địa chỉ")]
        public string diachi_kh { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        public string sdt_kh { get; set; }
        public int makh { get; set; }
        public string matkhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donhang> donhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon_bh> hoadon_bh { get; set; }
    }
}
