//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWatchers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheWatchersEntities : DbContext
    {
        public TheWatchersEntities()
            : base("name=TheWatchersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitietbanhang> chitietbanhangs { get; set; }
        public virtual DbSet<chitietdonhang> chitietdonhangs { get; set; }
        public virtual DbSet<chitietnhaphang> chitietnhaphangs { get; set; }
        public virtual DbSet<dongho> donghoes { get; set; }
        public virtual DbSet<dongho_seri> dongho_seri { get; set; }
        public virtual DbSet<donhang> donhangs { get; set; }
        public virtual DbSet<hoadon_bh> hoadon_bh { get; set; }
        public virtual DbSet<hoadon_nh> hoadon_nh { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<loai> loais { get; set; }
        public virtual DbSet<nhacungcap> nhacungcaps { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<thuonghieu> thuonghieux { get; set; }
        public virtual DbSet<hinhanh> hinhanhs { get; set; }
        public virtual DbSet<motachitiet> motachitiets { get; set; }
    }
}
